feat: add resolver for graphql api
nervosnet/godwoken_explorer pull request #312
Opened 2022-03-28 13:24 UTC by Naupio

2022-04-07 01:58 UTC, zmcNotafraid requested changes

2022-04-07 01:58 UTC, zmcNotafraid commented on lib/godwoken_explorer/graphql/resolovers/account.ex
> +  def account_udts(%Account{id: id}, _args, _resolution) do
所有的关于account 的相关的查询，user 是用eth_address, polyjuice_contract 使用 short_address, 用户默认是不知道id 的

2022-04-07 14:32 UTC, Naupio commented on lib/godwoken_explorer/graphql/resolovers/account.ex
> +  def account_udts(%Account{id: id}, _args, _resolution) do
这是 child fields 相关, 依赖于 parent object (在这里是 account), 这个不是 user 直接使用 args 的 resolver, 对于 user 的角度, 使用的的确是 eth_address 或者 short_address

2022-04-08 10:11 UTC, zmcNotafraid approved these changes

2022-04-08 10:11 UTC, merged